cores: 8
rerun-incomplete: True
software-deployment-method: apptainer
singularity-args: "--cleanenv --bind /home/andrei/Data/nano-cnv"
envvars:
  APPTAINER_CACHEDIR: /home/andrei/Data/singularity/cache
  APPTAINER_TMPDIR: /home/andrei/Data/singularity/tm