[workspace]
name = "tga_detection"
description = "tandem gene amplification detection"
version = "1.1.0"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
dry-run = "snakemake -n --cores 1 --use-conda --configfile config/config.yaml"
run-conda = "snakemake --cores 2 --sdm conda --configfile config/config.yaml"
run-apptainer = "snakemake --cores 2 --configfile config/config.yaml --profile profiles/apptainer_local"
rulegraph = { cmd = "dot -c && snakemake --rulegraph --configfile config/config.yaml | dot -Tsvg > images/rulegraph.svg" }
dag = { cmd = "dot -c && snakemake --dag --configfile config/config.yaml | dot -Tsvg > images/dag.svg" }


[dependencies]
snakemake = "==8.23.1"
snakefmt = ">=0.11.2,<0.12"
micromamba = ">=2.5.0,<3"
python-graphviz = ">=0.21,<0.22"
cairo = ">=1.18.4,<2"
pango = ">=1.56.4,<2"
python = ">=3.12.12,<3.13"
singularity = ">=2.4.6,<3"
conda = ">=25.11.1,<26"
