# table of samples and filepaths
sample_table: "config/samples_test.tsv"

# plasmid sequence location
plasmid: "resources/plasmid/CP061207.1.fasta"

# coordinates according to
# CP061207.1
# min read length
# defined as FR+IS+FR + 10%
min_read_len: 1820

# location of FRs
# FR length = 500 nt
# coordinates are included
fr_red_start: 2785
fr_red_end: 3285

fr_green_start: 114451
fr_green_end: 114951

# location of RU/IS
# the one closest to the RR
ru_start: 1955
ru_end: 2774

# location of blaSHV
bla_start: 1
bla_end: 861

# FR blast settings
format: 6
n_fr_aligns: 10000000
n_bla_aligns: 10000000

# FR/blaSHV/RU blast filtering
min_fr_len: 500
min_identity: 75
max_e_value: 0.00001
min_ru_len: 700
max_dist: 30
dist_to_end: 1320
# increase this value if the frequencies table contains NAs
max_cn: 60
# ru length
increment: 3450
# base length
base_len: 4299

# blaSHV plot
bla_len: 860

# bedtools merge
dist: 500