samples:
  76595_D_mh: 76595_D_mh
  # 76595_Exp1_MH: 76595_Exp1_MH

regions:
  CR1: CR1
  CR2: CR2
  CR3: CR3
  CR4: CR4

# location of DS: 3286-3289
# location of CRs
# CR length = 1678
# coordinates are included
cr1_start: 60155
cr1_end: 61832

cr2_start: 93175
cr2_end: 94852

cr3_start: 31478
cr3_end: 33155

cr4_start: 4726
cr4_end: 6403

# the same dist to DS as CR4 after DS
# i.e. 1437 nt
cr5_start: 171
cr5_end: 1849

n_cc_alns: 900000
format: 6