# table of samples and filepaths
sample_table: "config/samples_test.tsv"

# table of parameters
parameters: "config/params.tsv"

# plasmid sequence location
plasmid: "resources/plasmid/CP061207.1.fasta"

# blaSHV gene location
blaSHV: "resources/genes/blaSHV.fa"

# name for the frequencies table without the extension
output_name: "results/tables/frequencies_all_test"