samples:
  76595_D_mh: 76595_D_mh
  76595_Exp1_MH: 76595_Exp1_MH

regions:
# all coordinates relative to 
# the sequence deposited in NCBI (CP061207.1)
# same positions but length = 500 nt
  CR1:
    name: CR1
    start: 60155
    end: 60655
  CR2:
    name: CR2
    start: 93175
    end: 93675
  CR3:
    name: CR3
    start: 31478
    end: 31978
  CR4:
    name: CR4
    start: 3789
    end: 4289
  CR5:
    name: CR5
    start: 1109
    end: 1609

n_cc_alns: 900000
format: 6