# list of samples/replicates
samples: "configs/samples.txt"

# coordinates according to
# plasmid_DA61218_I-scel
# min read length
# defined as FR+IS+FR + 10%
min_read_len: 1820

# location of FRs
# FR length = 500 nt
# coordinates are included
fr_red_start: 32849
fr_red_end: 33349

fr_green_start: 24599
fr_green_end: 25099

# location of RU/IS
# the one closest to the RR
ru_start: 32019
ru_end: 32838

# location of blaSHV
bla_start: 30065
bla_end: 30925

# FR blast settings
format: 6
n_fr_aligns: 9000000
n_bla_aligns: 5000000

# FR/blaSHV/RU blast filtering
min_fr_len: 500
min_identity: 75
max_e_value: 0.00001
min_ru_len: 700
max_dist: 30
base_len: 1820
# increase this value if the frequencies table contains NAs
max_cn: 60
increment: 3450

# blaSHV plot
bla_len: 860

# bedtools merge
dist: 500
